Feature: Добавлена новая функциональность по хранению и сервису.
andreyTurkey/java-filmorate pull request #16
Opened 2023-04-04 06:28 UTC by andreyTurkey

2023-04-04 15:20 UTC, NikolaiDem requested changes

2023-04-04 15:20 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    FilmService filmService;
private

2023-04-04 15:20 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> getFilmByRating(@RequestParam(defaultValue = "10", required = false) Integer count) {
При указании дефолтного значения атрибут required лишний.

2023-04-04 15:20 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>  @Validated
Аннотация необходима, если в классе определены constraint annotations, например из javax.validation.constraints

2023-04-04 15:20 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>  @Validated
Аннотация необходима, если в классе определены constraint annotations, например из javax.validation.constraints

2023-04-04 15:20 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/exception/ErrorHundler.java
> +public class ErrorHundler {
ErrorHandler

2023-04-04 15:20 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService(InMemoryFilmStorage filmStorage, FilmRating filmRating) {
Сервис должен зависеть от интерфейсов классов-хранилищ, а не их реализаций

2023-04-04 15:20 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        film.getLikes().add(userId);
Методы добавления и удаления лайков лучше создать в классе Film и вызвать их здесь. Например, может измениться внутренняя реализация хранения лайков (List вместо Set), тогда придется менять и метод сервиса.

2023-04-04 15:20 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (!filmStorage.getFilms().containsKey(film.getId())) {
Лучше добавить метод existsBy(...) в репозиторий, который может проверить, существует ли объект с данным id. Так как реализация репозитория может быть in memory, а может быть БД или что-то еще.

2023-04-04 15:20 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (film.getLikes() == null) film.setLikes(new HashSet<>());
Лучше сделать так, чтобы film.getLikes() не возвращал null (проверять внутри метода)

2023-04-04 15:20 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private UserStorage userStorage;
Где-то используется ломбок (@FieldDefaults(level = AccessLevel.PRIVATE)), где-то явные private. Лучше привести к единообразию.

2023-04-04 15:20 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            } catch (NullPointerException ex) {
Перехватывать рантайм исключения в бизнес-коде плохая практика. Исправить везде)

2023-04-04 15:20 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                friend.getFriends().add(userId);
Сделать так, чтобы friend.getFriends() не возвращал null

2023-04-04 15:20 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +public interface FilmStorage {
В интерфейсе public для методов не нужен

2023-04-04 15:20 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    public Map<Integer, Film> getFilms();
Для чего этот метод в интерфейсе?

2023-04-04 15:20 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        List<Film> emptyFilms = new ArrayList<>(films.values());
Зачем использовать films.values(), если мапа пуста?

2023-04-04 15:20 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +        List<User> deletedUsers = new ArrayList<>(users.values());
Зачем использовать users.values(), если мапа пуста?

2023-04-04 15:20 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserStorage.java
> +    Map<Integer, User> getUsers();
Для чего этот метод в интерфейсе?

2023-04-04 15:20 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +            return user;
Можно сразу вернуть
            return users.remove(id);

2023-04-04 15:20 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +        return usersFromMap;
Можно сразу вернуть
        return new ArrayList<>(users.values());

2023-04-04 15:20 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        return allFilms;
Можно сразу вернуть
return new ArrayList<>(films.values())

2023-04-04 15:20 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +            return film;
Можно сразу вернуть
return films.remove(id);

2023-04-04 15:20 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (userStorage.getUsers().containsKey(userId)) {
В коде часто повторяется конструкция
if (userStorage.getUsers().containsKey(userId)) { }
Лучше вынести ее в отдельный метод.

2023-04-04 15:20 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (filmStorage.getFilms().containsKey(id)) {
В коде часто встречается конструкция 
 if (filmStorage.getFilms().containsKey(id)) { }
ЛУчше вынести ее в отдельный метод.

2023-04-04 15:20 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmRating.java
> +    private List<Film> filmsRating;
А какой профит вынести рейтинг в отдельный сервис?

2023-04-05 05:27 UTC, andreyTurkey commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmRating.java
> +    private List<Film> filmsRating;
Класс FilmRating хранит состояние, точнее еще одно хранилище фильмов с актуальной сортировкой. По примеру с FilmStorage хранение вынес в отдельный класс.

2023-04-05 19:16 UTC, NikolaiDem requested changes

2023-04-05 19:16 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService(InMemoryFilmStorage filmStorage, FilmRating filmRating) {
Не исправлено

2023-04-05 19:16 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        film.getLikes().add(userId);
Не исправлено

2023-04-05 19:16 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (film.getLikes() == null) film.setLikes(new HashSet<>());
Не исправлено

2023-04-05 19:16 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private UserStorage userStorage;
Не исправлено

2023-04-05 19:16 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                friend.getFriends().add(userId);
Не исправлено

2023-04-05 19:16 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            } catch (NullPointerException ex) {
Не исправлено

2023-04-05 19:16 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        List<Film> emptyFilms = new ArrayList<>(films.values());
Не исправлено

2023-04-05 19:16 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserStorage.java
> +    Map<Integer, User> getUsers();
Не исправлено

2023-04-05 19:16 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    public Map<Integer, Film> getFilms();
Не исправлено

2023-04-05 19:16 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +public interface FilmStorage {
Не исправлено

2023-04-05 19:16 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public boolean ifUserExists(Integer userId) {
private

2023-04-05 19:16 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmRating.java
> +    private List<Film> filmsRating;
Издалека напоминает CQRS паттерн, но выглядит избыточным в данном случае, так как создается дублирование без ощутимого преимущества. А еще в следующем спринте будет сохранение состояния в БД, и лайки будут записываться в отдельную таблицу, и в сохранении дублей фильмов не будет смысла)

2023-04-06 07:20 UTC, andreyTurkey commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmRating.java
> +    private List<Film> filmsRating;
Ок). Поскольку нам пока не известно дальнейшее развитие сервиса, решил сразу идти по пути разделения сервис - хранение. Сейчас перенес лайки в сервис.

2023-04-06 19:49 UTC, NikolaiDem requested changes

2023-04-06 19:49 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +public class FilmService implements FilmStorage {
Почему service реализует storage?

2023-04-06 19:49 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +public class FilmService implements FilmStorage {
Все служебные методы сделать private

2023-04-06 19:49 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +public class UserService implements UserStorage {
Почему service реализует storage?

2023-04-06 19:49 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                    String.format("Пользователя %d не существует.", friendId));
Но ведь может не существовать не только friendId ?

2023-04-06 19:49 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            throw new UserNotFoundException(String.format("Проверьте ID пользователей"));
Для чего String.format(...) ?

2023-04-06 19:49 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            throw new UserNotFoundException(String.format("Проверьте ID пользователей"));
Для чего String.format(...) ?

2023-04-06 19:49 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            throw new UserNotFoundException(String.format("Проверьте ID пользователей"));
Для чего String.format(...) ?

2023-04-06 19:49 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        return commonFreinds;
Можно сразу вычислить
return user.getFriends().stream()
                .filter(t -> friend.getFriends().contains(t))
                .map(userStorage::getUserById)
                .collect(Collectors.toList());

2023-04-06 19:49 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (userId <= 0) throw new UserNotFoundException(String.format("Пользователя %d  не существует", userId));
Положительность userId все равно не гарантирует, что пользователь существует.

2023-04-06 19:49 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +public class FilmService implements FilmStorage {
Везде, где проверяется существование фильма/юзера можно сделать метод как ...existsById(...), который внутри себя будет бросать исключение, если объект не найден. Тогда при валидации достаточно вызвать этот метод. А еще можно добавить генерацию исключения в метод getById(...), тогда и existsById(...) не понадобится

2023-04-06 19:49 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +public class UserService implements UserStorage {
Везде, где проверяется существование юзера можно сделать метод как ...existsById(...), который внутри себя будет бросать исключение, если объект не найден. Тогда при валидации достаточно вызвать этот метод. А еще можно добавить генерацию исключения в метод getById(...), тогда и existsById(...) не понадобится

2023-04-07 06:04 UTC, andreyTurkey commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    FilmService filmService;
Добавил в FilmController и UserController

2023-04-07 06:05 UTC, andreyTurkey commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>  @Validated
@Validated удалено

2023-04-07 06:06 UTC, andreyTurkey commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>  @Validated
@Validated удалено

2023-04-07 06:14 UTC, andreyTurkey commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +public class FilmService implements FilmStorage {
Согласен, исправил ошибку.

2023-04-07 06:31 UTC, andreyTurkey commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        return commonFreinds;
Отличная запись. Спасибо!

2023-04-07 07:25 UTC, andreyTurkey commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +public class FilmService implements FilmStorage {
Все таки оставлю ...existsById(...), потому что валидация нужна и в методах по удалению.

2023-04-30 11:41 UTC, merged